create table Txn_User(
UserID              	serial,  
UserName            	varchar(255),
Password            	varchar(1020),
LastName      		varchar(510),
MiddleName    		varchar(255),
FirstName     		varchar(255),
SalutationID		int,
CompanyName         	varchar(255),
DOB                     timestamp,
Age                     int,
GenderID                int,
MaritalStatusID         int,
ContactMobile       	varchar(255),
ContactMobile2      	varchar(255),
SecurityQuestionID  	int,
SecurityAnswer      	varchar(510),
RoleID              	INT,
IsActive            	BIT,
EmailID             	varchar(1020),
IsEMailIDConfirmed  	BIT,
IsAccountLocked	    	bit,
AccountLockDttm		timestamp,
AccountLockExpiryDttm	timestamp,
CreatedBy		int,
CreatedDate		timestamp,
LastModifiedBy		int,
LastModifiedDate	timestamp,
TCSignOffFlag		bit,
TCSignOffContentID	int,
CONSTRAINT Txn_User_pkey PRIMARY KEY (UserID) 

)

